# pre-commit-config.yaml

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: ^.*/data/.*$

-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
        exclude: ^.*/data/.*$

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        exclude: ^.*/data/.*$

-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        additional_dependencies: [toml]
        exclude: ^.*/?setup\.py$ ^.*/data/.*$

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'
    hooks:
    -   id: mypy
        exclude: ^.*/data/.*$
