# pre-commit-config.yaml

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
        exclude: ^.*/data/.*$

-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
        exclude: ^.*/data/.*$
        args: [-l 80, --experimental-string-processing]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'
    hooks:
    -   id: mypy
        exclude: ^.*/data/.*$
        additional_dependencies: [types-termcolor]
